version: "3"
services:

  mongo1:
    image: mongo:3.4
    command: mongod --smallfiles --replSet rs1 --noauth --nojournal --oplogSize 16
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongodata1:/data/db
      - mongoconfig1:/data/configdb
    networks:
      - overlay
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica == 1
  mongo2:
    image: mongo:3.4
    command: mongod --smallfiles --replSet rs1 --noauth --nojournal --oplogSize 16
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongodata2:/data/db
      - mongoconfig2:/data/configdb
    networks:
      - overlay
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica == 2

  mongo3:
    image: mongo:3.4
    command: mongod --smallfiles --replSet rs1 --noauth --nojournal --oplogSize 16
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongodata3:/data/db
      - mongoconfig3:/data/configdb
    networks:
      - overlay
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica == 3

networks:
  overlay:

volumes:
  mongodata1:
  mongodata2:
  mongodata3:
  mongoconfig1:
  mongoconfig2:
  mongoconfig3: