version: "3"
services:

  mongo:
    image: mongo:3.4
    command: mongod --smallfiles --replSet rs1 --dbpath /data/db --nojournal --oplogSize 16 --noauth
    environment:
      TERM: xterm
    labels:
      - "mongo.replica=$NODE_NUM"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "mongodata$NODE_NUM:/data/db"
      - "mongoconfig$NODE_NUM:/data/configdb"
    networks:
      - overlay

networks:
  overlay: