version: "3"
services:

  mongo:
    image: mongo:3.4
    command: mongod --smallfiles --replSet rs1 --dbpath /data/db --nojournal --oplogSize 16 --noauth
    environment:
      TERM: xterm
    labels:
      - "mongo.replica={REPLICA_SET}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data/db
    networks:
      - overlay
    ports:
      - 27017:27017

networks:
  overlay: