version: "3"
services:

  mongo:
    image: mongo:3.4
    command: mongod --smallfiles --replSet rs1 --dbpath /data/db --nojournal --oplogSize 16 --noauth
    environment:
      TERM: xterm
    labels:
      - "mongo.replica=${NODE}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongodata${NODE}:/data/db
      - mongoconfig${NODE}:/data/configdb
    networks:
      - overlay

networks:
  overlay: