version: "3"
services:

  mongo:
    image: mongo:3.4
    command: mongod --smallfiles --replSet rs1 --dbpath /data/db --nojournal --oplogSize 16 --noauth
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data/db